name = "ai-pun-generator"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_dir = "dist"

[[routes]]
pattern = "/*"
script = ""

[env.production]
workers_dev = true

[build.upload]
format = "service-worker"